import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffb95f',
        'on-secondary-fixed': '#002113',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#ffd4a4',
        'secondary-fixed-dim': '#4edea3',
        'surface-dim': '#d3daea',
        'on-secondary-fixed-variant': '#005236',
        'on-tertiary': '#ffffff',
        'surface-tint': '#4d44e3',
        'on-error': '#ffffff',
        'primary-fixed': '#e2dfff',
        'on-secondary-container': '#00714d',
        'primary-fixed-dim': '#c3c0ff',
        'surface-container-low': '#f0f3ff',
        error: '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#dce2f3',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#653e00',
        'on-surface': '#151c27',
        'on-primary-container': '#dad7ff',
        'on-primary-fixed': '#0f0069',
        'surface-bright': '#f9f9ff',
        shopbg: '#f9f9ff',
        'surface-container-highest': '#dce2f3',
        'surface-container-high': '#e2e8f8',
        'secondary-container': '#6cf8bb',
        'surface-container': '#e7eefe',
        surface: '#f9f9ff',
        outline: '#777587',
        'inverse-on-surface': '#ebf1ff',
        tertiary: '#684000',
        shopprimary: '#3525cd',
        'outline-variant': '#c7c4d8',
        'on-surface-variant': '#464555',
        'tertiary-fixed': '#ffddb8',
        'on-tertiary-fixed': '#2a1700',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#3323cc',
        'on-background': '#151c27',
        shopsecondary: '#006c49',
        'tertiary-container': '#885500',
        'error-container': '#ffdad6',
        'primary-container': '#4f46e5',
        'inverse-primary': '#c3c0ff',
        'secondary-fixed': '#6ffbbe',
        'inverse-surface': '#2a313d',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'pulse-dot': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.4' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;
